[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
fs_permissions = [{ access = "read", path = "./" }]   # allow reading files if needed
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]
gas_reports = ["*"]                                   # opt-in gas report

[rpc_endpoints]
hedera_testnet = "https://testnet.hashio.io/api"

[fmt]
line_length = 100
wrap_comments = true
