/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Agro } from "./Agro";
export * as factories from "./factories";
export { Agro__factory } from "./factories/Agro__factory";
